[package]
name = "url-shortener"
version = "0.1.0"
edition = "2024"

[dependencies]

axum = "0.8.4"
tokio = {version = "1.46.1", features = ["full"]}
serde = {version = "*", features = ["derive"]}
serde_json = "1.0.141"
